spring:
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION:43200000}

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        retry.backoff.ms: 1000
        spring.json.add.type.headers: false

logging:
  group:
    spring-context:
      - org.springframework.context
      - org.springframework.beans
      - org.springframework.boot.autoconfigure
    web:
      - org.springframework.web
      - org.springframework.web.servlet.DispatcherServlet
      - org.springframework.web.servlet.mvc.method.annotation
    security:
      - org.springframework.security
      - com.waregang.receiving_service.security
    db:
      - org.hibernate.SQL
      - org.hibernate.orm.jdbc.bind
      - org.springframework.transaction
      - org.flywaydb
    kafka:
      - org.springframework.kafka
      - org.apache.kafka.clients

  level:
    # Твой код всегда debug
    com.waregang: DEBUG

    # Группы — включаешь нужное, остальное off
    spring-context: off
    web: debug
    security: debug
    db: debug
    kafka: debug

pattern:
  console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n%ex{full}"


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true